### ISSUE TITLE
影视资源整合 | OHLIA

### ISSUE THREAD

**Issue by OHLIA** [OHLIA/gitment-comments#3]
https://ohlia.github.io/2018/03/06/found_media/

**Comment by OHLIA** [comment]
3/6
- 如果标题中含有方框如：'[任意文字]'，hexo g会出现问题
```
(node:1268) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Start processing
ERROR Process failed: _posts/found_media.md
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 5:
    date: 2018-03-06 22:43:22
        ^
    at generateError (D:\Documents\GitHub\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (D:\Documents\GitHub\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at readBlockMapping (D:\Documents\GitHub\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1046:9)
    at composeNode (D:\Documents\GitHub\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readDocument (D:\Documents\GitHub\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1492:3)
    at loadDocuments (D:\Documents\GitHub\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1548:5)
    at Object.load (D:\Documents\GitHub\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1569:19)
    at parseYAML (D:\Documents\GitHub\hexo\node_modules\hexo-front-matter\lib\front_matter.js:80:21)
    at parse (D:\Documents\GitHub\hexo\node_modules\hexo-front-matter\lib\front_matter.js:56:12)
    at Promise.all.spread (D:\Documents\GitHub\hexo\node_modules\hexo\lib\plugins\processor\post.js:52:20)
    at tryCatcher (D:\Documents\GitHub\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Documents\GitHub\hexo\node_modules\bluebird\js\release\promise.js:509:35)
    at Promise._settlePromise (D:\Documents\GitHub\hexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Documents\GitHub\hexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Documents\GitHub\hexo\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\Documents\GitHub\hexo\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (D:\Documents\GitHub\hexo\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (D:\Documents\GitHub\hexo\node_modules\bluebird\js\release\promise_array.js:144:14)
    at PromiseArray._iterate (D:\Documents\GitHub\hexo\node_modules\bluebird\js\release\promise_array.js:114:31)
    at PromiseArray.init [as _init] (D:\Documents\GitHub\hexo\node_modules\bluebird\js\release\promise_array.js:78:10)
    at Promise._settlePromise (D:\Documents\GitHub\hexo\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (D:\Documents\GitHub\hexo\node_modules\bluebird\js\release\promise.js:614:10)

```
